service: jackbnb
useDotenv: true

custom:
  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

package:
  excludeDevDependencies: false
  patterns:
    - '!.yarn/**'
    - '!.sonar/**'
    - '!.history/**'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    MONGO_URL: ${env:MONGO_URL}
    API_TOKEN: ${env:API_TOKEN}

functions:
  auth:
    handler: microservices/auth-ms/src/main.handler
    events:
      - http:
          path: auth/{proxy+}
          method: any
      - http:
          path: auth
          method: any
  properties:
    handler: microservices/properties-ms/src/main.handler
    events:
      - http:
          path: properties/{proxy+}
          method: any
      - http:
          path: properties
          method: any
