service: jackbnb-ms
useDotenv: true

plugins:
  - 'serverless-plugin-typescript'
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
  - serverless-offline

package:
  excludeDevDependencies: false
  patterns:
    - '!.yarn/**'
    - '!.sonar/**'
    - '!.history/**'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    MONGO_URL: ${env:MONGO_URL, 'mongodb://127.0.0.1:27017/jackbnb-ms'}
    API_TOKEN: ${env:API_TOKEN, 'jackbnb-dev-token'}

functions:
  jackbnb-rest-v1:
    handler: src/main.handler
    events:
      - http:
          path: api/v1/{proxy+}
          method: any
