service: jackbnb-ms
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
  - serverless-offline
  - serverless-plugin-warmup

package:
  excludeDevDependencies: false
  patterns:
    - '!.yarn/**'
    - '!.sonar/**'
    - '!.history/**'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    MONGO_URL: ${env:MONGO_URL}
    API_TOKEN: ${env:API_TOKEN}
    MONGO_CLUSTER: ${env:MONGO_CLUSTER}
    MONGO_DATABASE: ${env:MONGO_DATABASE}
    MONGO_PARAMS: ${env:MONGO_PARAMS}

functions:
  jackbnb-rest-v1:
    handler: src/main.handler
    events:
      - http:
          path: api/v1/{proxy+}
          method: any
