service: jackbnb-ms
useDotenv: true

plugins:
  - serverless-plugin-warmup
  - serverless-plugin-typescript
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
  - serverless-offline

package:
  excludeDevDependencies: false
  patterns:
    - '!.yarn/**'
    - '!.sonar/**'
    - '!.history/**'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    MONGO_URL: ${env:MONGO_URL}
    API_TOKEN: ${env:API_TOKEN}

functions:
  jackbnb-rest-v1:
    handler: src/main.handler
    vpc:
      securityGroupIds:
        - sg-0d382faddc97bd98a
      subnetIds:
        - subnet-0abe7779f1e65974b
    events:
      - http:
          path: api/v1/{proxy+}
          method: any
