name: Deploy
on:
  push:
    branches: [ main, microservices ]
env:
  MONGO_URL: ${{ secrets.MONGO_URL }}
  API_TOKEN: ${{ secrets.API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x
      - name: install lerna
        run: npm i -g lerna
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: bootstrap
        run: lerna bootstrap
      - name: deploy
        run: lerna run deploy
